scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-helm-api-operator/0.0.1/ibm-helm-api-operator.v0.0.1.clusterserviceversion.yaml"
