# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "helm-api"
  labels:
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: "{{ .Values.volumes.helmApiCertsSecretName }}"
  issuerRef:
    name: icp-ca-issuer
    kind: ClusterIssuer
  commonName: "helm-api"
  dnsNames:
  - helm-api.kube-system
  - helm-api.kube-system.svc
  - localhost
  - 127.0.0.1
